---
title: "Machine learning"
author: "Vee Mabasa"
date: '2022-06-27'
output: word_document
---


```{r}
library(tidyverse)
library(caret)
library(ggpubr)
library(kernlab)
```

```{r}

library(readxl)
TB_cytotoxicity <- read_excel("G:/My Drive/Colab Notebooks/dataTB1/TB_cytotoxicity.xlsx", 
    range = "a2:e132")
View(TB_cytotoxicity)
```


```{r}
TB_cytotoxicity[['Class']] <- as.factor(TB_cytotoxicity[['Class']])
TB_cytotoxicity[['MW']] <- as.numeric(TB_cytotoxicity[['MW']])
TB_cytotoxicity[["LogP"]] <- as.numeric(TB_cytotoxicity[["LogP"]])
TB_cytotoxicity[['NumHDonors']] <- as.numeric(TB_cytotoxicity[["NumHDonors"]])
TB_cytotoxicity[["NumHAcceptors"]] <- as.numeric(TB_cytotoxicity[["NumHAcceptors"]])
View(TB_cytotoxicity)
```

```{r}
TB_cytotoxicity <- data.frame(as.list(TB_cytotoxicity))
TB_cytotoxicity
```


#performstratified random split of the dataset
```{r}

set.seed(100)

TrainingIndex <- createDataPartition(TB_cytotoxicity[['Class']], p=0.8, list = FALSE)
Trainingset <- TB_cytotoxicity[TrainingIndex,]
Testingset <- TB_cytotoxicity[-TrainingIndex,]
```



#Build training model
```{r}

model <-train(Class ~.,data = Trainingset, method = "svmPoly",
              preProcess=c("scale", "center"), trControl= trainControl(method = "none"),
              tuneGrid= data.frame(degree=1 , scale=1, C=1))

```


#Build CV model
```{r}
model.cv <- train(Class ~., data = Trainingset, method ="svmPoly",
                  preProcess = c("scale", "center"), trControl= trainControl(method = "cv",number = 10),
                  tuneGrid= data.frame(degree=1, scale=1, C=1))
```


#Apply mode for prediction
```{r}
model.training <- predict(model, Trainingset)
model.testing <- predict(model, Testingset)
model.cv <- predict(model.cv, Trainingset)
```


#model performance (display confusion matrix and statistics)
```{r}
model.training.confusion <- confusionMatrix(model.training, Trainingset[['Class']])
model.testing.confusion <- confusionMatrix(model.testing, Testingset[['Class']])
model.cv.confusion <- confusionMatrix(model.cv, Trainingset[['Class']])
```


# Print models
```{r}
print(model.training.confusion)
print(model.testing.confusion)
print(model.cv.confusion)
```


#feature importance
```{r}
importance <- varImp(model)
importance
```

```{r}
plot(importance)
```

```{r}
saveRDS(model, "model.rds")
```

```{r}
library(shiny)
library(data.table)
library(caret)
```

```{r}

# Read in the SVM model
model <- readRDS("model.rds")


####################################
# User interface                   #
####################################

ui <- pageWithSidebar(
  
  # Page header
  headerPanel('Vusi TB_inh Predictor'),
  
  # Input values
  sidebarPanel(
    #HTML("<h3>Input parameters</h3>"),
    tags$label(h3('Input parameters')),
    numericInput("MW", 
                 label = "MW", 
                 value = ""),
    numericInput("LogP", 
                 label = "LogP", 
                 value = ""),
    numericInput("NumHDonors", 
                 label = "NumHDonors", 
                 value = ""),
    numericInput("NumHAcceptors", 
                 label = "NumHAcceptors", 
                 value = ""),
    
    actionButton("submitbutton", "Submit", 
                 class = "btn btn-primary")
  ),
  
  mainPanel(
    tags$label(h3('Status/Output')), # Status/Output Text Box
    verbatimTextOutput('contents'),
    tableOutput('tabledata') # Prediction results table
    
  )
)

####################################
# Server                           #
####################################

server<- function(input, output, session) {
  
  # Input Data
  datasetInput <- reactive({  
    
    df <- data.frame(
      Name = c("MW",
               "LogP",
               "NumHDonors",
               "NumHAcceptors"),
      Value = as.character(c(input$MW,
                             input$LogP,
                             input$NumHDonors,
                             input$NumHAcceptors)),
      stringsAsFactors = T)
    
    Class <- 0
    df <- rbind(df, Class)
    input <- transpose(df)
    write.table(input,"input.csv", sep=",", quote = FALSE, row.names = FALSE, col.names = FALSE)
    
    test <- read.csv(paste("input", ".csv", sep=""), header = TRUE)
    
    Output <- data.frame(Prediction=predict(model,test), round(predict(model,test,type="prob"), 10))
    print(Output)
    
  })
  
  # Status/Output Text Box
  output$contents <- renderPrint({
    if (input$submitbutton>0) { 
      isolate("Calculation complete.") 
    } else {
      return("Server is ready for calculation.")
    }
  })
  
  # Prediction results table
  output$tabledata <- renderTable({
    if (input$submitbutton>0) { 
      isolate(datasetInput()) 
    } 
  })
  
}

####################################
# Create the shiny app             #
####################################
shinyApp(ui = ui, server = server)

```


